# Generated by Django 4.2.9 on 2024-01-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="React",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employees", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
            ],
        ),
    ]
